version: 2
jobs:
  build:
    docker:
      - image: node:11-slim
    steps:
      - checkout
      - run:
          name: Install markdownlint
          command: npm install -g markdownlint-cli
      - run:
          name: Check for Lint
          command: markdownlint .
